---
- name: Generate Cert Authority on localhost
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - debug: var=cert
    - debug: var=key     

    - name: Creates keys directory
      file:
        path: ./.keys
        state: directory

    - name: check if CA exists 
      stat: 
        path: ./.keys/ca-config.json
      register: ca_authority

    - name: Generate local CA authority
      shell: cd .keys ; echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' | cfssl gencert -initca - | cfssljson -bare ca - ; echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
      when: ca_authority.stat.exists==false

    - name : Generate etcd client cert
      environment:
        NAME: "client"
      shell:  cd .keys; echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="" -profile=client - | cfssljson -bare $NAME


- name: Install CA 
  hosts:  backends,agents
  become: true
  vars:
    ca_path_debian: /usr/local/share/ca-certificates
    ca_path:
      RedHat:
        6: /usr/local/share/ca-certificates
        7: /etc/pki/ca-trust/source/anchors
      Debian:
        7: '{{ ca_path_debian }}'
        8: '{{ ca_path_debian }}'

  tasks:
  - name: Make /etc/sensu/certs directory
    file:
      path: /etc/sensu/certs
      state: directory

  - name: install ca package on rhel systems
    yum:
      name: ca-certificates
      state: present
    when: ansible_os_family == "RedHat"

  - name: install ca package on debian systems
    apt:
      name: ca-certificates
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: enable dynamic ca configuration on rhel6
    shell: /bin/update-ca-trust enable
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

  - name: copy certificate authority to trusted ca path of the os
    copy:
      src: '{{ item }}'
      dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/'
      owner: root
      group: root
      mode: 0644
    with_fileglob:
      - .keys/ca.pem
    notify:
      - update trusted ca debian
      - update trusted ca redhat
  
  - name: verify certificate authority
    command: "openssl verify {{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/ca.pem"
    changed_when: false


  handlers:
  - name: update trusted ca debian
    shell: /usr/sbin/update-ca-certificates
    when: ansible_os_family == "Debian"

  - name: update trusted ca redhat
    shell: /bin/update-ca-trust
    when: ansible_os_family == "RedHat"


- name: Install, configure and run Sensu backend
  hosts: backends
  become: true

  tasks:
    - name : Set ipaddr
      set_fact: 
        ipaddr: "{{ ansible_host }}"
      when: ipaddr is undefined
    - name : Set etcd_name 
      set_fact: 
        etcd_name: "{{ inventory_hostname_short }}"
      when: etcd_name is undefined

    - name: Generate backend cert
      delegate_to: localhost
      become: false
      environment:
        ADDRESS: "{{ ipaddr }},{{ etcd_name }}"
        NAME: "{{ etcd_name }}"
      shell: cd .keys; echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="$ADDRESS" -profile=peer - | cfssljson -bare $NAME

    - name: Install backend cert
      copy:
        src: ".keys/{{ etcd_name }}.pem"
        dest: /etc/sensu/certs/
        owner: sensu 
        group: sensu
        mode: 0644
    - name: Install backend cert key
      copy:
        src: ".keys/{{ etcd_name }}-key.pem"
        dest: /etc/sensu/certs/
        owner: sensu 
        group: sensu
        mode: 0644
    - name: verify backend cert
      command: "openssl verify -CAfile /etc/pki/ca-trust/source/anchors/ca.pem /etc/sensu/certs/{{ etcd_name }}.pem"
      changed_when: false

    - name: Install etcd client cert
      copy:
        src: ".keys/client.pem"
        dest: /etc/sensu/certs/
        owner: sensu 
        group: sensu
        mode: 0644
    - name: Install etcd cert key
      copy:
        src: ".keys/client-key.pem"
        dest: /etc/sensu/certs/
        owner: sensu 
        group: sensu
        mode: 0644
    - name: verify etcd client cert
      command: "openssl verify -CAfile /etc/pki/ca-trust/source/anchors/ca.pem /etc/sensu/certs/client.pem"
      changed_when: false

    #- namie: Install etcd client cert

    - name: Install backend
      include_role:
        name: sensu.sensu_go.backend
      vars:
        version: 5.16.1
        cluster_admin_username: tadej
        cluster_admin_password: my.password  # USE VAULT IN REAL SCENARIOS!!!
        backend_config:
          log-level: info
          etcd-name: "{{ etcd_name }}"
          etcd-initial-advertise-peer-urls: "https://{{ ipaddr }}:2380"
          etcd-advertise-client-urls: "http://{{ ipaddr }}:2379"
          etcd-listen-peer-urls: "https://0.0.0.0:2380"
          etcd-listen-client-urls: "http://0.0.0.0:2379"
          etcd-initial-cluster-token: ""
          etcd-initial-cluster-state: "new"
          #etcd-cert-file: "/etc/sensu/certs/client.pem"
          #etcd-key-file: "/etc/sensu/certs/client-key.pem"
          #etcd-client-cert-auth: "true"
          #etcd-trusted-ca-file: "/etc/pki/ca-trust/source/anchors/ca.pem"
          etcd-peer-cert-file: "/etc/sensu/certs/{{ etcd_name }}.pem"
          etcd-peer-key-file: "/etc/sensu/certs/{{ etcd_name }}-key.pem"
          etcd-peer-client-cert-auth: "true"
          etcd-peer-trusted-ca-file: "/etc/pki/ca-trust/source/anchors/ca.pem"
          etcd-initial-cluster: "sensu-cluster0=https://192.168.50.20:2380,sensu-cluster1=https://192.168.50.21:2380,sensu-cluster2=https://192.168.50.22:2380"

- name: Install, configure and run Sensu agent 
  hosts: agents
  become: true
  tasks:
    - name : Generate agent mtls cert
      delegate_to: localhost
      become: false
      environment:
        NAME: "{{ etcd_name }}"
      shell: echo "here"
        #echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="" -profile=client - | cfssljson -bare $NAME


